CREATE TABLE FEIRA_LIVRE (
        ID INT PRIMARY KEY,
        LONGITUDE INT NOT NULL,
        LATITUDE INT NOT NULL,
        SETCENS BIGINT NOT NULL,
        AREAP BIGINT NOT NULL,
        CODDIST INT NOT NULL,
        DISTRITO VARCHAR(50) NOT NULL,
        CODSUBPREF INT NOT NULL,
        SUBPREFE VARCHAR(50) NOT NULL,
        REGIAO5 VARCHAR(10) NOT NULL,
        REGIAO8 VARCHAR(10) NOT NULL,
        NOME_FEIRA VARCHAR(50) NOT NULL,
        REGISTRO CHAR(6) NOT NULL,
        LOGRADOURO VARCHAR(255) NOT NULL,
        NUMERO VARCHAR(50),
        BAIRRO VARCHAR(50) NOT NULL,
        REFERENCIA VARCHAR(255)
) ;
